services:
  micro-ros:
    network_mode: host
    privileged: true
    image: microros/micro-ros-agent:iron
    command: serial --dev /dev/ttyTHS1 -v6
    volumes:
    - /dev/:/dev/
  ros2:
    network_mode: host
    privileged: true
    build:
      context: docker/ros2/rolling
      args:
        - user_id=1001
        - ros_ws=/home/ubuntu/dev_ws

    # Enabling GPU access with Compose
    # https://docs.docker.com/compose/gpu-support/
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #          - capabilities: [gpu]
    #            count: all

    environment:
      # Set a fancy prompt (See ~/.bashrc in the container)
      - TERM=xterm-256color

      # WSLg settings
      # https://www.reddit.com/r/bashonubuntuonwindows/comments/n2nthu/can_i_use_the_new_wslg_with_docker/
      - DISPLAY
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR
      - PULSE_SERVER
    volumes:
      - ./:/home/ubuntu/project
      - ./dev_ws:/home/ubuntu/dev_ws
      - ./docker/ros2/.ros:/home/ubuntu/.ros
      - ./docker/ros2/.gazebo/:/home/ubuntu/.gazebo
      - /dev/:/dev/

      # WSLg settings
      - /mnt/wslg:/mnt/wslg
      - /tmp/.X11-unix:/tmp/.X11-unix
